services:
  backend:
    container_name: taskflow-api
    build:
      context: .
      dockerfile: ./src/TaskFlow.Api/Dockerfile
    ports:
      - "${API_HTTP_PORT}:${API_HTTP_PORT}"
      - "${API_HTTPS_PORT}:${API_HTTPS_PORT}"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERTIFICATE_PATH}
      - ConnectionStrings__DevelopmentConnection=Server=${DB_SERVER};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True;
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/:ro
    networks:
      - taskflow-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    container_name: taskflow-web
    build:
      context: ./src/TaskFlow.Web
      dockerfile: Dockerfile
    ports:
      - "${WEB_HTTP_PORT}:80"
      - "${WEB_HTTPS_PORT}:443"
    depends_on:
      - backend
    networks:
      - taskflow-network
    volumes:
      - ${ANGULAR_CERTS_PATH}:/etc/nginx/certs:ro
      - ${NGINX_CONFIG_PATH}:/etc/nginx/conf.d/default.conf

networks:
  taskflow-network:
    driver: bridge
