services:
  backend:
    container_name: taskflow-api
    build:
      context: .
      dockerfile: ./src/TaskFlow.Api/Dockerfile
    ports:
      - "7000:7000"
      - "7443:7443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:7000;https://+:7443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=YourSecurePassword123!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings__DevelopmentConnection=Server=host.docker.internal;Database=TaskFlow-dev;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https/:ro
    networks:
      - taskflow-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
   
  frontend:
    container_name: taskflow-web
    build:
      context: ./src/TaskFlow.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
      - "4443:443"
    depends_on:
      - backend
    networks:
      - taskflow-network
    volumes:
      - ./src/TaskFlow.Web/.angular-certs:/etc/nginx/certs:ro
      - ./src/TaskFlow.Web/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  taskflow-network:
    driver: bridge