services:
  backend:
    container_name: taskflow-api
    build:
      context: .
      dockerfile: ./src/TaskFlow.Api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DevelopmentConnection=Server=host.docker.internal;Database=TaskFlow-dev;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    networks:
      - taskflow-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
   
  frontend:
    container_name: taskflow-web
    build:
      context: ./src/TaskFlow.Web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - taskflow-network
    volumes:
      - ./src/TaskFlow.Web/nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  taskflow-network:
    driver: bridge