name: Docker Build & Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/taskflow-api
  IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/taskflow-web

jobs:
  backend:
    name: Build & Push Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Backend Image
        run: |
          docker build -t $IMAGE_BACKEND:latest -f src/TaskFlow.Api/Dockerfile .
          docker tag $IMAGE_BACKEND:latest $IMAGE_BACKEND:${{ github.sha }}

      - name: Push Backend Image
        run: |
          docker push $IMAGE_BACKEND:latest
          docker push $IMAGE_BACKEND:${{ github.sha }}

  frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Build Frontend Image
        run: |
          docker build -t $IMAGE_FRONTEND:latest -f src/TaskFlow.Web/Dockerfile src/TaskFlow.Web
          docker tag $IMAGE_FRONTEND:latest $IMAGE_FRONTEND:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push $IMAGE_FRONTEND:latest
          docker push $IMAGE_FRONTEND:${{ github.sha }}
